http4s/http4s-jdk-http-client

build.sbt
core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala

update to http4s 0.20

---

build.sbt

@amesgen started this module and certainly belongs in the POM if he wants credit.  Leaving this one for his review.

Credit @amesgen: he wrote most of it!

---

.travis.yml

Maybe this will fix the inversion we're seeing [here](https://travis-ci.org/http4s/http4s-jdk-http-client/builds/536373703)?

Make stages explicit

---

project/plugins.sbt

Remove unused sbt-jmh plugin

---

build.sbt

`/stable` will always point to the latest non-qualified tag in the docs.

Generate /stable redirect in docs

---

build.sbt

I did this ad hoc to get 0.2.0-M4 out the door.  Let's get it properly into the build.

Publish with sonatype bundles

---

core/src/main/scala/org/http4s/client/jdkhttpclient/JdkWSClient.scala

When closing the WS connection in the resource finalizer there might be an exception. Maybe there is an additional, helpful exception stuck in the queue (received in `onError` in the JDK WS listener), so we rethrow it. So this change improves diagnostics in some rare cases.
Initially discussed in #116

rethrow more exceptions when finalizing a ws connection

---

build.sbt

I've had to do this manually the last couple times.

Use sonatypeBundleRelease as a release step

---

.github/workflows/snapshots.yml

Should fix #147, in addition to updating the secret, which is already done.

Fix inappropriate ioctl for device when publishing snapshots.

---

.github/workflows/snapshots.yml

simplify gpg workaround

---

.gitignore
build.sbt

Trivial change to close #146 (in combination with #153). I can't test this, but it seems fine.

add site publishing as a release step

---

.mergify.yml

add mergify for scala-steward

---

.github/workflows/ci.yml
dhall/ci.dhall

sometimes, errors are ignored
https://github.com/amesgen/http4s-jdk-http-client/runs/553344900#step:12:1
We can try this again when it is stable.

move away from sbt thin client

---

docs/src/main/mdoc/index.md

document spurious deadlocks with Java 11 and TLS 1.3

---

core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala

A bit surprising that noone ran into this before.
Thanks @Billzabob for discovering this [here](https://github.com/http4s/http4s-jdk-http-client/issues/200#issuecomment-608196475)!

fix connection leak if body is not consumed

---

core/src/main/scala/org/http4s/client/jdkhttpclient/JdkWSClient.scala

ignore output closed exception

---

.github/workflows/ci.yml
.github/workflows/release.yml
project/build.sbt

This should fix the release workflow.

update-dhallj to 0.3.0

---

project/Dhall.scala
project/build.sbt

Closes fthomas/scala-steward#1512

only require Java 8 for the sbt project

---

CHANGELOG.md

Closes #321
I hope I got everything from https://github.com/http4s/http4s-jdk-http-client/compare/v0.3.1...master

update changelog for 0.3.2

---

build.sbt

follow up to #343, see the recent comments there

filter empty tags

---

build.sbt

remove settings (upstreamed to sbt-http4s-org)

---

core/src/test/scala/org/http4s/client/jdkhttpclient/JdkWSClientSpec.scala

echo.websocket.org has caused more and more timeouts recently

use a local echo server for testing

---

.github/workflows/ci.yml
build.sbt

https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash

fix sbt deprecations

---

.github/workflows/ci.yml
build.sbt
core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/client/jdkhttpclient/WSClient.scala
core/src/test/scala/org/http4s/client/jdkhttpclient/JdkHttpClientSpec.scala
core/src/test/scala/org/http4s/client/jdkhttpclient/JdkWSClientSpec.scala

* scala-3.0.0-RC2
* cats-2.5.0
* cats-effect-2.4.1
* fs2-2.5.4
* scodec-1.1.25
* http4s-0.22.0-M7
* vault-2.1.9
* case-insensitive-1.1.2

support Scala 3.0.0-RC2, update all the deps

---

core/src/main/scala/org/http4s/jdkhttpclient/AlwaysCancelingSubscriber.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkWSClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/WSClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/package.scala
core/src/test/scala/org/http4s/jdkhttpclient/BodyLeakExample.scala
core/src/test/scala/org/http4s/jdkhttpclient/CompletableFutureTerminationTest.scala
core/src/test/scala/org/http4s/jdkhttpclient/DeadlockWorkaround.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkHttpClientSpec.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala
core/src/test/scala/org/http4s/jdkhttpclient/Shifting.scala
docs/src/main/mdoc/index.md

change package structure to org.http4s.jdkhttpclient --- series/0.4

---

.github/workflows/ci.yml
build.sbt
project/build.properties
project/plugins.sbt

sbt-http4s-org: 0.8.1
sbt-mdoc: 2.2.21
http4-client: 0.21.24
fs2-core: 2.5.6
cats: 2.6.1
cats-effect: 2.5.1
scodec-bits: 1.1.27
spec2: 4.12.0
cats-effect-testing-specs2: 0.5.4
java-Websocket: 1.5.2
JDK 16
Sbt 1.5.2

Bump versions

---

.github/workflows/ci.yml
.mergify.yml
build.sbt
core/src/test/scala/org/http4s/jdkhttpclient/BodyLeakExample.scala
core/src/test/scala/org/http4s/jdkhttpclient/CompletableFutureTerminationTest.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala

After this is merged, I will create series/0.5 from current main with this commit (with http4s-0.23.0-RC1 instead).

update to http4s-1.0.0-M23 and co

---

CHANGELOG.md
build.sbt

Release v0.4.0

---

build.sbt
docs/src/main/mdoc/index.md

echo.websocket.org is no longer available

Use local echo server in the docs

---

.mergify.yml

Update to #555, I forgot to do this once again.

Update Scala to 2.13.8 in Mergify config

---

.envrc
flake.lock
flake.nix

~~TODO: `java --version` still prints the version of my global java~~

Use typelevel-nix

---

.github/workflows/ci.yml
build.sbt
docs/README.md
docs/index.html
project/plugins.sbt

Towards https://github.com/http4s/http4s-jdk-http-client/issues/563. /cc @rossabaker
I pushed this to the gh-pages on my fork, have a look:
https://armanbilge.github.io/http4s-jdk-http-client

Setup versioned documentation

---

docs/README.md

This can hold us over until the stable release.

Use `@SNAPSHOT_VERSION@` in docs

---

build.sbt
core/src/test/scala/org/http4s/jdkhttpclient/JdkHttpClientSpec.scala

Re-add tests for `JdkHttpClient`

---

.mergify.yml
build.sbt

Just one of those annoying things :)

Fix mergify config

---

docs/README.md

docs: fix rendering of WS frame hierarchy

---

core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkWSClient.scala
docs/README.md

Addresses https://github.com/http4s/http4s-jdk-http-client/pull/874#issuecomment-1556068884, h/t @hnaderi.

Set default `connectTimeout` in `defaultHttpClient`

---

core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkWSClient.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkHttpClientSpec.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala

h/t @hnaderi for reporting in https://github.com/http4s/http4s-jdk-http-client/pull/874#issuecomment-1556068884.
tl;dr we were making the requests uncancelable by mistake 🙃

Fix cancelation in http and ws clients

---

.github/workflows/ci.yml
.mergify.yml
.scalafmt.conf
CHANGELOG.md
build.sbt
core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
core/src/test/scala/org/http4s/jdkhttpclient/BodyLeakExample.scala
core/src/test/scala/org/http4s/jdkhttpclient/CompletableFutureTerminationTest.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala
docs/README.md

I screwed up. this was the wrong branch

Revert "Merge to main"

---

build.sbt
flake.lock
project/build.properties

To prepare to make a new 1.0-Milestone release
no conflicts in the merge

Merge series/0.9 to main

---

project/build.properties
project/plugins.sbt

Assembles #1187, #1189, and #1190, none of which can go alone.

Make publishable on Central Portal
