.travis.yml

Trusty hit EOL on April 30,  2019, and it's still ambiguous what Travis CI's default is.

Explicitly use xenial

---

CODE_OF_CONDUCT.md

1. Link to http4s' copy, because it has our moderators
2. Link to our moderators, so if we add and remove any, it's not a pain as we go polyrepo
I'm assuming for now that moderators will be from the organization pool, even if individual modules get their own committers.

Clean up Code of Conduct links

---

.travis.yml

This is why the [master publish is failing.](https://travis-ci.com/http4s/http4s-jdk-http-client/jobs/202380021#L231)

Semi-colons aren't needed from the shell

---

core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala

[Oops](https://travis-ci.org/http4s/http4s-jdk-http-client/jobs/536301055#L245).

Fix broken Scaladoc references

---

.travis.yml

Can't publish to Sonatype without it, so we should be testing it on every cross build.  See #22.

Test scaladoc on each build

---

.travis.yml
build.sbt

Depends on PGP_SECRET and PGP_PASSPHRASE, which I've already set up in Travis CI.
For posterity's sake: using key 3C477ED52BBC57DDE7D1FC8A14E4D722E40D4E4F

Import the gpg key

---

build.sbt

When we added the cross build override for docs, we broke this.

Fix supported Scala versions in docs

---

.travis.yml

https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
But I see no reason not to do all of .cache for futureproofing.

Update coursier cache location

---

CHANGELOG.md
build.sbt

We missed the most important upgrade of all. I'll release this as 0.2.0-RC2.

Upgrade to http4s-0.21.0-RC1

---

.github/workflows/snapshots.yml

Shell scripts in YAML, what could go wrong?

Unescape the quotations in ssh-agent eval

---

.github/workflows/snapshots.yml
build.sbt

Site publishing did not work previously (see [gh-pages log](https://github.com/http4s/http4s-jdk-http-client/commits/gh-pages), [error message](https://github.com/http4s/http4s-jdk-http-client/runs/421426336?check_suite_focus=true#step:6:119)).
I am not sure why this fails (the job does not fail as sbt-ghpages [swallows the error](https://github.com/sbt/sbt-ghpages/blob/master/src/main/scala/com/typesafe/sbt/sbtghpages/GhpagesPlugin.scala#L95-L98)), but this workaround does work, and I think it is in fact "better" that local publishing uses the local github user information and not "GitHub Actions CI". The commit message for local publishing will be "updated site" ([src](https://github.com/sbt/sbt-ghpages/blob/master/src/main/scala/com/typesafe/sbt/sbtghpages/GhpagesPlugin.scala#L85)).

fix site publishing

---

build.sbt
version.sbt

Move sonatypeBundleRelease ahead of bumping the version number, or else it fails to find the bundle to release.
Move it ahead of site publication, so we don't advertise a release that doesn't exist. (Even though we'll still advertise it before it syncs to Maven Central.)

Move sonatypeBundleRelease step

---

CHANGELOG.md

I should have done this before the release.  
In the http4s-core repo, there is a single changelog, but it leads to a complicated split process between shared pages and version-specific pages.  We only have the latter, which simplifies publishing, but makes it hard to correct docs after the tag like this.  Something to ponder.

Missing changelog for 0.2.0-RC5

---

.github/workflows/ci.yml
.github/workflows/snapshots.yml

- We now use `github.run_id` instead of `github.action`
- We use a weekly cache that uses the cache of the week before. This way, we always have a reasonably fresh cache which neither does grow without bounds nor does reset if any sbt or project/*.scala file is changed.

change caching strategy & use actual build number

---

docs/src/main/mdoc/index.md

Motivated by [this](https://gitter.im/http4s/http4s?at=5e5e5f41b873303e27785323).
Editing this markdown file is a pain due to articifial line breaks, do we want to do something about it (-> long lines)?

mention restricted headers

---

build.sbt
project/build.sbt

paradox-material-theme uses an ancient circe version (jonas/paradox-material-theme#25). Downgrading circe results in jawn conflicts.
I initially suggested temporarily not using this theme, but I ran into other issues there too... [gitter](https://gitter.im/http4s/http4s-dev?at=5e850f164ed72e126b8a3044)
This should fix snapshot publishing.

use upickle instead of circe in sbt

---

core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/client/jdkhttpclient/JdkWSClient.scala
core/src/test/scala/org/http4s/client/jdkhttpclient/DeadlockWorkaround.scala
docs/src/main/mdoc/index.md

Frankly, I don't have the motiviation to debug #200 again. I just pray that this bug magically disappears by a Java 11 or cats-effect update.
The only people who are negatively affected by this change are people who use a default client to connect to a server which only supports TLSv1.3 on Java 11 (mentioning the `SSLHandshakeException` here so that it can be googled). I think this is pretty rare.
Please intervene if you liked the previous state (warning in the docs, no built-in workaround) more. Personally, I am very slightly in favor of this PR.
Closes #200

workaround for #200

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.mergify.yml
dhall/ci.dhall
dhall/common.dhall
dhall/javaVersions.dhall
dhall/mergify.dhall
dhall/release.dhall

- Use the excellent [coursier/cache-action](https://github.com/coursier/cache-action). Additionally, this fixes these [deprecation warnings](https://github.com/http4s/http4s-jdk-http-client/actions/runs/297494035).
- Java 14 -> 15
- Dependabot will update the version numbers for external GH actions (e.g. if a new major versionf or coursier/cache-action is released).
I also ran `dhall format` on all files for consistency.

Some CI tweaks

---

core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/client/jdkhttpclient/JdkWSClient.scala
core/src/main/scala/org/http4s/client/jdkhttpclient/package.scala
core/src/test/scala/org/http4s/client/jdkhttpclient/CompletableFutureTerminationTest.scala

This commit adds a new function `fromCompletableFutureShift` and replaces the usage of `fromCompletionStage` with this function.
This function is similar to `fromCompletionStage`, except that it brackets on the effect, ensuring that in the case of cancellation or error the `CompletableFuture` is terminated with `.cancel` or `.completeExceptionally`.
Failing to do this, as `fromCompletionStage` did, can lead to a resource leak and extra CPU cycles when the effect which results from `fromCompletionStage` is terminated due to some external condition, e.g. `.timeout`.
To verify this, one needs only replace `fromCompletableFutureShift` in `CompletableFutureTerminationTest` with `org.http4s.internal.fromCompletionStage` and run the test.

Terminate CompletableFuture Values In All Exit States

---

core/src/main/scala/org/http4s/client/jdkhttpclient/AlwaysCancelingSubscriber.scala
core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
core/src/test/scala/org/http4s/client/jdkhttpclient/BodyLeakExample.scala

From the JDK docs for HttpResponse#BodyHandlers.ofPublisher,
https://docs.oracle.com/en/java/javase/15/docs/api/java.net.http/java/net/http/HttpResponse.BodyHandlers.html#ofPublisher()
> When the HttpResponse object is returned, the response headers will have been completely read, but the body may not have been fully received yet. The HttpResponse.body() method returns a Publisher<List<ByteBuffer>> from which the body response bytes can be obtained as they are received. The publisher can and must be subscribed to only once.
Of particular note is the final sentence, "The publisher can and must be subscribed to only once.".
There is a much longer discussion on the semantics of this in the comments in the code, but the short version is that we must always ensure that the `Flow.Publisher` …

Fix Resource Leak When The HTTPResponse Body Is Not Read

---

.github/workflows/ci.yml
build.sbt

see djspiewak/sbt-spiewak#44
In particular, snapshots are not released as such, but rather as "normal" releases, see https://search.maven.org/artifact/org.http4s/http4s-jdk-http-client_2.12/0.3-4-1910a08/jar

disable snapshot publishing for now

---

.github/workflows/ci.yml
build.sbt

Revert #341, by inlining the "original" definition of `isSnapshot` from sbt-git: https://github.com/sbt/sbt-git/blob/c97aca2577d8ca36d04859cb1bbcc6d8cdb0bece/src/main/scala/com/typesafe/sbt/SbtGit.scala#L187-L189

reenable snapshot publishing

---

.github/workflows/ci.yml
build.sbt

- actually run in *all* branches (@rossabaker noticed this in http4s)
- do not publish documentation for snapshots on the `series/*` branches

prepare CI for multi-branch setup

---

build.sbt

It turns out that (contrary to the documentation in the README), sbt-sonatype actually checks for the `-SNAPSHOT` suffix...
https://github.com/xerial/sbt-sonatype/blob/2f148bf1cbaf56fbf8a2534d9947305670dcd3f7/src/main/scala/xerial/sbt/Sonatype.scala#L110
Sorry for the CI PR churn!

append -SNAPSHOT to version

---

core/src/main/scala/org/http4s/client/jdkhttpclient/package.scala

We need to shift _immediately_ after the `F.async` call.

Shift Immediately After The F.async Call

---

core/src/main/scala/org/http4s/jdkhttpclient/AlwaysCancelingSubscriber.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkWSClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/WSClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/package.scala
core/src/test/scala/org/http4s/jdkhttpclient/BodyLeakExample.scala
core/src/test/scala/org/http4s/jdkhttpclient/CompletableFutureTerminationTest.scala
core/src/test/scala/org/http4s/jdkhttpclient/DeadlockWorkaround.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkHttpClientSpec.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala
docs/src/main/mdoc/index.md

change package structure to org.http4s.jdkhttpclient

---

build.sbt
core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
docs/README.md

I'm not 100% sure on this change yet, but I'm pretty sure this executor is not used for blocking operations. In which case, we should definitely prefer to use the Cats Effect compute pool here. It means one less threadpool in the application and thus less contention and less page faults, which is a big win.
```java
/**
* Sets the executor to be used for asynchronous and dependent tasks.
*
* <p> If this method is not invoked prior to {@linkplain #build()
* building}, a default executor is created for each newly built {@code
* HttpClient}.
```
https://github.com/openjdk/jdk11/blob/37115c8ea4aff13a8148ee2b8832b20888a5d880/src/java.net.http/share/classes/java/net/http/HttpClient.java#L253

Use Cats Effect EC as `HttpClient` executor

---

build.sbt
core/src/test/scala/org/http4s/jdkhttpclient/JdkHttpClientSpec.scala

This also includes a merge from [`series/0.7`](https://github.com/http4s/http4s-jdk-http-client/tree/series/0.7).

Update http4s to v1.0.0-M33

---

CHANGELOG.md

I think it makes sense to stop listing dependency patch bumps.

Update changelog for v1.0.0-M3

---

build.sbt
core/src/test/scala/org/http4s/jdkhttpclient/BodyLeakExample.scala
core/src/test/scala/org/http4s/jdkhttpclient/CompletableFutureTerminationTest.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala
docs/README.md

Now that blaze is schismed, the dependency is more of a burden here. This is especially a problem on main, because it means the jdk-http-client is blocked from updating to the latest http4s milestone until blaze itself has updated and released, which may not be straightforward.

Migrate to ember

---

.github/workflows/ci.yml
build.sbt
core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
docs/index.html
project/plugins.sbt

Upstream PR:
- https://github.com/typelevel/fs2/pull/3102
Previously interop was done through the reactive-streams converter, but now FS2 can interop directly with the JDK9+ interfaces. So we can remove a layer of cruft 😆

Migrate to new FS2 `j.u.c.Flow` interop APIs

---

core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala

Http/2 is always streaming, so setting content-length is optional.

Handle http/2 request body without content-length

---

.github/workflows/ci.yml
.mergify.yml
build.sbt
core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala
core/src/main/scala/org/http4s/jdkhttpclient/JdkWSClient.scala
core/src/test/scala/org/http4s/jdkhttpclient/BodyLeakExample.scala
core/src/test/scala/org/http4s/jdkhttpclient/DeadlockWorkaround.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkHttpClientSpec.scala
core/src/test/scala/org/http4s/jdkhttpclient/JdkWSClientSpec.scala
docs/README.md

A bit complicated merge in JdkHttpClient.
Please review

Merge series/0.10 to main
